version: 2
updates:
  - package-ecosystem: pip
    directory: "AppFastApi"
    schedule:
      interval: daily
      time: "02:00"
    open-pull-requests-limit: 10
    labels:
      - 'type: dependencies'
