version: '0.10'
services:
  crypto-pro:
    container_name: crypto-pro
    image: armrus/cryptopro-pycades:latest
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 80
    restart: always
    ports:
      - '8095:80'
