name: Build
on:
  push:
#    branches:
#      - main
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
#  release:
#    name: release
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: conventional Changelog Action
#        id: changelog
#        uses: TriPSs/conventional-changelog-action@v3
#        with:
#          github-token: ${{ secrets.github_token }}
#          output-file: CHANGELOG.md
#          release-count: 0
#          skip-version-file: true
#          skip-git-pull: true
#      - name: Create a GitHub release
#        uses: ncipollo/release-action@v1
#        with:
#          tag: ${{ steps.changelog.outputs.tag }}
#          name: Release ${{ steps.changelog.outputs.tag }}
#          body: ${{ steps.changelog.outputs.changelog }}

  build_cryptopro:
    name: Build cryptopro
    needs: release
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up Docker builder
        uses: docker/setup-buildx-action@v1
      - name: Log in to the Cntainer registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extra metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}