name: Build
on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build_cryptopro:
    name: Build cryptopro
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to the Cntainer registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extra metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/cryptopro
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          secrets: |
            'GH_TOKEN=${{ secrets.GITHUB_TOKEN }}'
          build-args: 'github_token=${{ secrets.GITHUB_TOKEN }}'
          tags: |
            ghcr.io/devind-team/cryptopro-pycades:v${{ steps.package-version.outputs.current-version}}
            ghcr.io/devind-team/cryptopro-pycades:latest